name: Run JavaScript Tests

on:
  pull_request:
    branches: [master]

jobs:
  check_javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/node-setup@v1
        with:
          node-version: 14
      - name: Install dependencies and run tests
        run: |
          cd codeSnippets
          cd javascript
          yarn install
          yarn run test
